[project]
name = "betedge-processing"
version = "0.1.0"
description = "BetEdge data processing and silver layer transformations"
requires-python = ">=3.11"
dependencies = [
    "betedge-data",
    "polars>=1.31.0",
    "pyarrow>=20.0.0",
]

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/betedge_processing"]

[tool.hatch.metadata]
allow-direct-references = true