[project]
name = "betedge-data"
version = "0.1.0"
description = "BetEdge data access and client library"
requires-python = ">=3.11"
dependencies = [
    "httpx[http2]>=0.28.1",
    "pydantic-settings>=2.10.0",
    "ijson>=3.2.0",
    "pyarrow>=20.0.0",
    "orjson>=3.10.12",
    "minio>=7.2.0",
    "pydantic>=2.11.7",
    "boto3>=1.34.0",
    "polars>=1.31.0",
    "python-dotenv>=1.1.1",
]

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/betedge_data"]

[tool.hatch.metadata]
allow-direct-references = true